### ISSUE TITLE
[BUG] There is an issue in the Validate function where it panics, root cause is in the runSession function

### ISSUE THREAD

**Issue by rahultyagidev** [truemail-rb/truemail-go#80]
The bug is in the runSession function when creating smtp client we ignore the error, however calling either Send or Close in case there is an error causes panic

### New bug checklist

- [x] I have updated `truemail-go` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-go/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-go)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-go/issues)

### Bug description
The bug is in the runSession function when creating smtp client we ignore the error on line 105, however calling either Send or Close in case there is an error causes panic:
<img width="1030" alt="Screenshot 2023-10-12 at 4 52 50 PM" src="https://github.com/truemail-rb/truemail-go/assets/143419133/2f426057-cf92-4ed4-9cd8-d9144dcf20d9">

**Comment by bestwebua** [comment]
Hi, @rahultyagidev! Thanks for your report. I'll take a look deeply.

**Comment by RichiMaulana** [comment]
Hi, is there any update on this case/bug reports?

Recently I also stumbling into the same issue where the module will resulting runtime error.

The runtime error only happen when initial connection to MX server is failed/instantly rejected.

I do some testing to actually handle the smtp.NewClient error in _smtp_client.go_ instead of ignoring it, below are the changes:

before:
`
client, _ := smtp.NewClient(connection, smtpClient.targetServerAddress)
`

after:
`client, err := smtp.NewClient(connection, smtpClient.targetServerAddress)
// Handle connection to MX failed
if err != nil {
	closeConnection()
	return false
}
`

IDK if that's the correct/best solution or not, but when I try to reproduce the error again using my test above the error is not appearing again.

**Comment by RichiMaulana** [comment]
Hi, is there any update on this case/bug reports?

Recently I also stumbling into the same issue where the module will resulting runtime error.

The runtime error only happen when initial connection to MX server is failed/instantly rejected.

I do some testing to actually handle the smtp.NewClient error in _smtp_client.go_ instead of ignoring it, below are the changes:

before:
```golang
client, _ := smtp.NewClient(connection, smtpClient.targetServerAddress)
```

after:
```golang
client, err := smtp.NewClient(connection, smtpClient.targetServerAddress)
// Handle connection to MX failed
if err != nil {
	closeConnection()
	return false
}
```

IDK if that's the correct/best solution or not, but when I try to reproduce the error again using my test above the error is not appearing again.

**Comment by bestwebua** [comment]
@RichiMaulana The real cause of this error was the wrong SMTP service ready status 🥇
